version: latest
services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./scripts/db:/scripts/db/
    command:
      /scripts/db/init.sh