version: latest
services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - "27017:27017"
    # networks: 
    #   - mongo-network

  # mongo_init:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.init
  #   environment:
  #     - MONGO_HOST=mongo
  #   networks:
  #     - mongo-network

  mongo_seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

# networks:
#   mongo-network: